#pragma once

typedef enum {
	ERR_OK = 0,						// No error
	ERR_OUT_OF_MEMORY,				// Segfault
	ERR_FILE_NOT_FOUND,
	ERR_INVALID_FORMAT,
	ERR_INVALID_ARGUMENT,			// Invalid argument (often when NULL)
	ERR_INVALID_TYPE,
	ERR_UNEXPECTED_RESULT,			// When a value returned by a function isn't expected
	ERR_CPU_INSTRUCTION_NOT_FOUND,
	ERR_COP0_INSTRUCTION_NOT_FOUND,
	ERR_GP0_COMMAND_NOT_FOUND,
	ERR_GP1_COMMAND_NOT_FOUND,
	ERR_WRITE_NOT_ALLOWED,
	ERR_WRITE_SECTION_NOT_FOUND,
	ERR_WRITE_ADDRESS_NOT_ALIGNED,
	ERR_WRITE_SECTION_NOT_CONNECTED,
	ERR_READ_NOT_ALLOWED,
	ERR_READ_SECTION_NOT_FOUND,
	ERR_READ_SECTION_NOT_CONNECTED,
	ERR_BUS_SECTION_NOT_FOUND,
	ERR_READ_ADDRESS_NOT_ALIGNED,
    ERR_BUS_SECTION_NOT_CONNECTED,
	ERR_INTENTIONAL_STOP
} Error;

const char *error_string(int err);
